# TOML configuration document
title = "Directory, Rat, Analysis, and Plotting Configurations"

[data_dirs]
# OpenEphys folders below (list of strings)
# should have the "Record Node ###" folder inside it
OE = [
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-06-03_19-41-47',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-06-06_15-21-22',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-06-06_15-45-13',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-06-06_16-01-57',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-06-08_14-14-30',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-07-15_15-16-47',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-11-16_16-19-28',
    '/snel/share/data/rodent-ephys/open-ephys/treadmill/2022-11-17_17-08-07',
    ]
# KiloSort folders below (list of strings)
# should have the "Record Node ###" folder inside it, and
# "KilosortResults" in the "recording99" folder
KS = [
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/pipeline/godzilla/2022-11-16_16-19-28_myo',
    '/snel/share/data/rodent-ephys/open-ephys/treadmill/pipeline/godzilla/2022-11-17_17-08-07_myo',
    # '/snel/share/data/rodent-ephys/open-ephys/treadmill/pipeline/cleopatra/2022-07-15_15-16-47_myo/'
    ]
# Anipose folders below (list of strings)
# should have the pose-3d folder inside it
anipose = [
    # '/snel/share/data/anipose/session20220603',
    # '/snel/share/data/anipose/session20220606',
    # '/snel/share/data/anipose/session20220608',
    # '/snel/share/data/anipose/session20220715',
    # '/snel/share/data/anipose/session20220914',
    # '/snel/share/data/anipose/session20221116',
    # '/snel/share/data/anipose/session20221117',
    '/snel/share/data/anipose/session20221220_128test/'
]

[rat]
### Rat-specific configurations
[rat.cleopatra]
bodyparts_list = ['palm_L_y']#,'palm_L_z','palm_R_z']#,'mtar_L_y','mtar_R_y']#['palm_L_y', 'palm_L_z','palm_R_y', 'palm_R_z']#['mtar_L_y','mtar_L_z','mtar_R_y','mtar_R_z'] #['palm_L_y']
bodypart_for_alignment = ['palm_L_y']
session_date=['20220715']
treadmill_speed=[20]
treadmill_incline=[15]
camera_fps=125 #125 FPS
vid_length=10 #10/20 seconds

[rat.dogerat]
bodyparts_list = ['palm_R_y','palm_R_z']#,'palm_L_z','palm_R_z']#,'mtar_L_y','mtar_R_y']#['palm_L_y', 'palm_L_z','palm_R_y', 'palm_R_z']#['mtar_L_y','mtar_L_z','mtar_R_y','mtar_R_z'] #['palm_L_y']
bodypart_for_alignment = ['palm_R_y']
session_date=['20220603']
treadmill_speed=[20]
treadmill_incline=[0]
camera_fps=100 #100 FPS
vid_length=20 #10/20/30 seconds

[rat.godzilla]
bodyparts_list = ['palm_L_y','palm_R_y','mtar_L_y','mtar_R_y']#,'palm_L_z','palm_R_z']#,'mtar_L_y','mtar_R_y']#['palm_L_y', 'palm_L_z','palm_R_y', 'palm_R_z']#['mtar_L_y','mtar_L_z','mtar_R_y','mtar_R_z'] #['palm_L_y']
bodypart_for_alignment = ['palm_L_y']
session_date = ['20221117-4']
treadmill_speed = [10]
treadmill_incline = [0]
camera_fps = 125 #125 FPS
vid_length = 60 #30/60 seconds

[analysis]
MU_spike_amplitudes_list = [[150.0001,500],[500.0001,1700],[1700.0001,5000]]
ephys_channel_idxs_list = [13,16]#[7]#[13]#[2,4,5,7,8,11]#[1,2,3,4,13,14]
filter_ephys = 'notch' # 'bandpass' # 'both' # notch is 60Hz and bandpass is 350-7000Hz
sort_method = 'kilosort' # 'kilosort'/'thresholding'
bodypart_for_reference = 'tailbase' # choose bodypart to use as origin, without _x/_y/_z suffix, plug into origin_offsets as a value to subtract for that coordinate
bodypart_ref_filter =  2 #Hz, Boolean/int Example: (False to disable filtering of bodypart_for_reference, 2 for 2Hz cutoff lowpass)
filter_all_anipose = 0 # 'highpass', 'median', or Boolean
trial_reject_bounds_mm = [[-15,15],[-15,15]] #mm, Boolean/Integer/2D List, rejects trials outside bounds of the trial average at each bodypart's alignment timepoint. Examples: Boolean / 40 / [[10,40],[-10,25]] for peak, trough values
trial_reject_bounds_sec = [0,0.500] #seconds, time window of step duration outside of which trials get rejected. Examples: [0, 0.550] or [0.550, 0.6]
origin_offsets = [-18,'tailbase',135] # Values recorded from origin to treadmill bounds, bodypart string, or use zeroes for no offset. If bodypart_for_reference is set for one coordinate, it overrides setting and will subtract for that coordinate. Examples: [-18,211,135]/[-87,211,135]/[52,-310,0]/['nose','tailbase',135], can be disbaled with disabled with 0
save_binned_MU_data = 0 # set Boolean
time_frame = [0.05,0.15] # 2-element list slicing between 0 and 1, e.g., [0,.5], set to 1 for full ephys plotting
bin_width_ms = 10
smoothing_window = [10,10,10,10] # bins
phase_align = 1 # set Boolean, pertains to process_spikes.smooth() and process_spikes.state_space()
align_to = 'foot off' # "foot strike"/"foot off"

[plotting]
### Plotting parameters
plot_type = "sort" # MU_space_stepwise # behavioral_space # sort # bin_and_count # pandas_eda # multi_bin # multi_state_space
plot_units = [0,1,2,3,4]
do_plot = 1 # set Boolean, whether to actually generate plots
N_colors = 16 #len(MU_spike_amplitudes_list)*len(ephys_channel_idxs_list)+len(bodyparts_list)
plot_template = 'plotly_white'
Possible_Themes =['ggplot2','seaborn','simple_white','plotly','plotly_white','plotly_dark',
                    'presentation','xgridoff','ygridoff','gridon','none']
qual_dict_keys = ['Paired', 'Pastel1', 'Set1', 'Set3']
div_dict_keys = ['BrBG', 'PRGn', 'PiYG', 'PuOr', 'RdBu', 'RdGy', 'RdYlBu', 'RdYlGn', 'Spectral']
seq_dict_keys = ['Blues', 'BuGn', 'BuPu', 'GnBu', 'Greens', 'Greys', 'OrRd', 'Oranges', 'PuBu', 'PuBuGn', 'PuRd', 'Purples', 'RdPu', 'Reds', 'YlGn', 'YlGnBu', 'YlOrBr', 'YlOrRd']
